### ISSUE TITLE
Decorate all routes using Walk

### ISSUE THREAD

**Issue by ledor473** [opentracing-contrib/go-gorilla#4]
I was looking to use this library but we have a lot of routes configured in our project and wrapping every single one of them makes the code much harder to read than it currently is.

While it's not fully tested yet, it seems pretty easy to decorate all routes using the `Walk` function:

```go
_ = r.Walk(func(route *mux.Route, router *mux.Router, ancestors []*mux.Route) error {
	route.Handler(
		nethttp.Middleware(tracer, route.GetHandler(), nethttp.OperationNameFunc(someFuncToExtractOperationName)))
	return nil;
})
```

Do you feel that adding an exported function that does the above would fit in this library?  
The line seems very simple to me, so maybe this would better fit in the README?

**Comment by yurishkuro** [comment]
+1
